Migration to H2 DB back-end (not complete). Added SSL support to web server. Added feature to generate self-signed certificate via Bouncy Castle for use in embedded Jetty server (still needs to be persisted in DB for reuse). Still getting error when running Maven build (not getting from eclipse run): java.lang.NoClassDefFoundError: Could not initialize class gnu.io.CommPortIdentifier (due to RXTX installation and only thrown when RXTX is not previously installed)