Migration to H2 DB back-end (not complete). Updated BeanPathAdaptor to fix issues with switching beans that caused a ClassCastException, but still needs feature to bind to multiple JFX control properties and a way to detect updates made to the POJO fields. Still getting error when running Maven build (not getting from eclipse run): java.lang.NoClassDefFoundError: Could not initialize class gnu.io.CommPortIdentifier (due to RXTX installation and only thrown when RXTX is not previously installed)