Migration to H2 DB back-end (not complete). Updated BeanPathAdaptor to add a feature to bind to multiple JFX control properties to it, but still needs a way to detect updates made to the POJO fields. Still getting error when running Maven build (not getting from eclipse run): java.lang.NoClassDefFoundError: Could not initialize class gnu.io.CommPortIdentifier (due to RXTX installation and only thrown when RXTX is not previously installed)