Migration to H2 DB back-end (not complete). Added authentication for MD5 and SHA-256 (still needs some tweaking in JPALoginService). Still getting error when running Maven build (not getting from eclipse run): java.lang.NoClassDefFoundError: Could not initialize class gnu.io.CommPortIdentifier (due to RXTX installation and only thrown when RXTX is not previously installed)