Migration to H2 DB back-end (not complete). Added a way to pass a signature algorithm into the web server. Still getting error when running Maven build (not getting from eclipse run): java.lang.NoClassDefFoundError: Could not initialize class gnu.io.CommPortIdentifier (due to RXTX installation and only thrown when RXTX is not previously installed)