Migration to H2 DB back-end (not complete). Completed authentication using MD5 with Jetty and JPA (SHA-256 not available in all browsers yet). Still getting error when running Maven build (not getting from eclipse run): java.lang.NoClassDefFoundError: Could not initialize class gnu.io.CommPortIdentifier (due to RXTX installation and only thrown when RXTX is not previously installed)