Migration to H2 DB back-end (not complete). Updated web server key store persistence in DB for reuse (still needs password encryption for key store). Still getting error when running Maven build (not getting from eclipse run): java.lang.NoClassDefFoundError: Could not initialize class gnu.io.CommPortIdentifier (due to RXTX installation and only thrown when RXTX is not previously installed)