Migration to H2 DB back-end (not complete). Started JavFX PathProperty that will allow for a path to be given that will auto generate a JavaFX property as well as being one-way binding that will update the model when the JavaFX control is updated. Still getting error when running Maven build (not getting from eclipse run): java.lang.NoClassDefFoundError: Could not initialize class gnu.io.CommPortIdentifier (due to RXTX installation and only thrown when RXTX is not previously installed)